# Generated by Django 4.0.5 on 2022-06-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='image',
            new_name='content_image',
        ),
    ]
