# Generated by Django 4.0.5 on 2022-06-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_image_art_content_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Art',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content_image',
            new_name='content_img',
        ),
    ]
